let num = 10;
console.log(num);
let first = 5;
let second = 10;
console.log(first + second);
console.log(first - second);
console.log(first * second);
console.log(first / second);
let bar = 20;
let qwerty = 5;
let res = bar - qwerty - 10;
let end = res - qwerty;
let str = 'Hello, Palmo.';
alert(str);
let name = 'Жан';
let age = '18';
alert('Я ' + name + ' мне ' + age + '.');
function timeCounter() {
    const SEC_IN_HOUR = 3600;
    const secInDay = SEC_IN_HOUR * 24;
    const secInMonth = secInDay * 30;
    console.log('sec in hour ' + SEC_IN_HOUR);
    console.log('sec in day ' + secInDay);
    console.log('sec in month ' + secInMonth);
}
timeCounter();
let number = 5;
number = Math.pow(number, 2);
let d = 8;
let n = Math.pow(d, 2);
let x = Math.pow(d, 3);